// This file is auto generated by build/build-entry.js
import { VueConstructor } from 'vue/types';
import Lazyload from './lazyload';
import Locale from './locale';
import SessionTitle from './session-title';
import TestComponent from './test-component';

declare global {
  interface Window {
    Vue?: VueConstructor;
  }
}

const version = '0.1.0';
const components = [
  SessionTitle,
  TestComponent
];

const install = (Vue: VueConstructor) => {
  components.forEach(Component => {
    Vue.use(Component);
  });
};

/* istanbul ignore if */
if (typeof window !== 'undefined' && window.Vue) {
  install(window.Vue);
}

export {
  install,
  version,
  Lazyload,
  Locale,
  SessionTitle,
  TestComponent
};

export default {
  install,
  version
};
