// This file is auto generated by build/build-entry.js
import { VueConstructor } from 'vue/types';
import De from './de';
import Lazyload from './lazyload';
import Locale from './locale';

declare global {
  interface Window {
    Vue?: VueConstructor;
  }
}

const version = '2.3.0-beta.2';
const components = [
  De
];

const install = (Vue: VueConstructor) => {
  components.forEach(Component => {
    Vue.use(Component);
  });
};

/* istanbul ignore if */
if (typeof window !== 'undefined' && window.Vue) {
  install(window.Vue);
}

export {
  install,
  version,
  De,
  Lazyload,
  Locale
};

export default {
  install,
  version
};
